from enum import Enum

class ReportType(Enum):
    SHORT_REPORT = 1
    LONG_REPORT = 2
    ONELINE_LONG_REPORT = 3


# System configuration
LINUX_IMAGE_PATH = 'Linux_kernel_image/Linux_image_6_1_14_RV32IMA_NoMMU'
DEVICE_TREE_PATH = 'Linux_kernel_image/device_tree_binary.dtb'
LINKER_MAP_FILE_PATH = 'Linux_kernel_image/debug_info/System.map'

TEST_UART_INPUT = "ls -lah / \r\n"

RAM_SIZE = 64*1024*1024
START_ADDRESS_OF_RAM  = 0x80000000
START_ADDRESS_OF_UART = 0x10000000
START_ADDRESS_OF_TIMER_CLINT = 0x11000000

# Debug options configuration
TTY_OUTPUT_ENABLED = True

LOGGER_PRINT_DEVICE_ACTIVITY = False
LOGGER_PRINT_CSR_REGISTER_ACTIVITY = False

LOGGER_REPORT_TYPE = ReportType.SHORT_REPORT

START_TRACEOUT_AT_INSTRUCTION_NO = None
EXIT_EMULATOR_AT_INSTRUCTION_NO  = 67750000
BREAKPOINT_AT_INSTRUCTION_NO = None


# Generate CPU state output for all instructions
if 0:
    START_TRACEOUT_AT_INSTRUCTION_NO = 0
    EXIT_EMULATOR_AT_INSTRUCTION_NO  = 63000000
    LOGGER_REPORT_TYPE = ReportType.ONELINE_LONG_REPORT
    TTY_OUTPUT_ENABLED = False
