
LINUX_IMAGE_PATH = 'Linux_kernel_image/Linux_image_6_1_14_RV32IMA_NoMMU'
DEVICE_TREE_PATH = 'Linux_kernel_image/device_tree_binary.dtb'

RAM_SIZE = 64*1024*1024
START_ADDRESS_OF_RAM = 0x80000000

START_ADDRESS_OF_UART = 0x10000000

START_TRACEOUT_AT_INSTRUCTION_NO = 3267960
LOGGER_SHORT_REPORT = False
LOGGER_SHORT_REPORT = True

LOGGER_PRINT_DEVICE_ACTIVITY = False
LOGGER_PRINT_CSR_REGISTER_ACTIVITY = False

